### ISSUE TITLE
I think i liked it i will change my mind maybe

### ISSUE THREAD

**Issue by Vigeza** [karakasEnes/github-test-project#2]
I think i liked it i will change my mind maybe

_Originally posted by @karakasEnes in https://github.com/karakasEnes/github-test-project/issues/1#issuecomment-1168335003_

**Comment by karakasEnes** [comment]
what is this

**Comment by Vigeza** [comment]
> what is this

best issue ever

**Comment by karakasEnes** [comment]
I am closing this bs
